/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    kotlin("jvm") version "1.9.23"
    id("application")   
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("it.unibo.jakta:jakta-dsl:0.9.1")
}

application {
    mainClass = "it.unibo.jakta.testing.MainKt"  
}
